spring.application.name=banco-feira

spring.datasource.url=jdbc:mysql://localhost:3306/feira_gastronomica?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=arthur1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

jwt.secret=V4doO2RxQk9R/2F0mikMMChnIjnvJbFHWjcXgGQr0TI=

cors.allowed-origins=http://localhost:4200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naoResponda.feiraADM@gmail.com
spring.mail.password=zofw xgbm dqoi unpm 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

